#!/usr/bin/env python3
"""
merge_state.py: resolve the rebase conflicts a concurrent publish creates.

WHY THIS EXISTS
  The brief's push is race-safe by design: main can move while a run is working, so a
  rejected push rebases and retries. That comment in the workflow claimed the retry was
  "conflict-free in practice, because content commits are additive new files". Half true.
  site/content/ IS additive and never conflicts. The other three staged paths are not:

    editorial-log.json         appended by every run
    regwatch.json              rewritten by every run
    site/data/chartmaster.json regenerated by every run

  So the moment two runs overlap, the rebase stops on a content conflict, the step exits
  non-zero, and the run's verified stories are lost. That is what killed the 2026-07-29
  16:24 brief, right after --autostash cleared the previous failure in the same step.

  These files are not prose. Nobody needs to read a conflict and decide: each one has a
  single correct resolution, and this script applies it so the retry can finish.

HOW EACH ONE MERGES, and why
  editorial-log.json          A log of what each run approved and rejected. Two runs each
                              wrote a real entry, so the union is the answer. Taking either
                              side would silently delete the other run's editorial record,
                              which is the one file where that matters most. Deduped on
                              exact content, ordered by date.
  regwatch.json               A tracker keyed by "jurisdiction :: instrument". Union of
                              keys; on a collision keep the entry seen more recently and
                              union its dates, because both sides observed real sightings.
  site/data/chartmaster.json  One generated snapshot of the desk's read, not a record.
                              There is nothing to merge, so the later date wins and on a
                              tie UPSTREAM wins. That direction is deliberate: upstream
                              landed while this run was still working, so its read is the
                              later one, and letting our older snapshot overwrite it would
                              make the board go backwards. Losing this run's snapshot costs
                              nothing, because the next run regenerates it from live data.

SAFETY
  Only these three paths are ever resolved. A conflict anywhere else is a real conflict
  that a human should see, and this script refuses to touch it and exits non-zero so the
  rebase stays stopped and the workflow fails loudly.

USAGE, from inside a stopped rebase
  python3 merge_state.py && git add <paths> && git rebase --continue
"""

import json
import subprocess
import sys

# The only paths this script will resolve. Anything else conflicting is a real conflict.
KNOWN = ("editorial-log.json", "regwatch.json", "site/data/chartmaster.json")


def _stage(path, n):
    """One side of the conflict straight from the index, so conflict markers in the
    working file never have to be parsed."""
    r = subprocess.run(["git", "show", f":{n}:{path}"], capture_output=True, text=True)
    if r.returncode != 0 or not r.stdout.strip():
        return None
    try:
        return json.loads(r.stdout)
    except json.JSONDecodeError:
        return None


def conflicted():
    r = subprocess.run(["git", "diff", "--name-only", "--diff-filter=U"],
                       capture_output=True, text=True, check=True)
    return [p for p in r.stdout.split("\n") if p.strip()]


def merge_editorial_log(upstream, replayed):
    """Union of run records, deduped on exact content, ordered by date.

    Dates repeat by design (one entry per slot per day), so dedup is on the whole record
    rather than on the date, and a genuinely identical record from both sides collapses
    to one."""
    seen, out = set(), []
    for entry in (upstream or []) + (replayed or []):
        key = json.dumps(entry, sort_keys=True)
        if key not in seen:
            seen.add(key)
            out.append(entry)
    return sorted(out, key=lambda e: str(e.get("date", "")))


def merge_regwatch(upstream, replayed):
    """Union of tracked measures. Both sides watched real feeds, so neither set of
    sightings may be dropped; on a shared key the later last_seen wins and dates union."""
    out = dict(upstream or {})
    for k, t in (replayed or {}).items():
        o = out.get(k)
        if not o:
            out[k] = t
            continue
        keep = t if str(t.get("last_seen", "")) > str(o.get("last_seen", "")) else o
        merged = dict(keep)
        dates = list(dict.fromkeys(list(o.get("dates") or []) + list(t.get("dates") or [])))
        if dates:
            merged["dates"] = dates
        first = [d for d in (o.get("first_seen"), t.get("first_seen")) if d]
        if first:
            merged["first_seen"] = min(first)
        out[k] = merged
    return out


def merge_chartmaster(upstream, replayed):
    """Not a merge: a snapshot. Later date wins, and on a tie UPSTREAM wins.

    Note the direction, and note that it is the opposite of what "prefer our own work"
    would suggest. Upstream pushed while this run was still working, so upstream's read is
    the later one; preferring our older snapshot would walk the board backwards. Nothing
    is lost either way, because the next run regenerates this file from live data."""
    if not replayed:
        return upstream
    if not upstream:
        return replayed
    return replayed if str(replayed.get("date", "")) > str(upstream.get("date", "")) else upstream


MERGERS = {
    "editorial-log.json": merge_editorial_log,
    "regwatch.json": merge_regwatch,
    "site/data/chartmaster.json": merge_chartmaster,
}


def main():
    paths = conflicted()
    if not paths:
        print("merge_state: nothing conflicted")
        return 0

    unknown = [p for p in paths if p not in KNOWN]
    if unknown:
        print(f"::error::merge_state: refusing to auto-resolve a real conflict in "
              f"{', '.join(unknown)}. Only {', '.join(KNOWN)} have a deterministic "
              f"resolution; this one needs a human.")
        return 1

    for p in paths:
        # During a rebase, stage 2 is the upstream side and stage 3 is the commit being
        # replayed, which is this run's work. Named for what they mean here.
        upstream, mine = _stage(p, 2), _stage(p, 3)
        if upstream is None and mine is None:
            print(f"::error::merge_state: neither side of {p} parsed as JSON")
            return 1
        merged = MERGERS[p](upstream, mine)
        with open(p, "w", encoding="utf-8") as f:
            json.dump(merged, f, indent=1, ensure_ascii=False, sort_keys=(p != "editorial-log.json"))
            f.write("\n")
        size = len(merged) if isinstance(merged, (list, dict)) else 1
        print(f"merge_state: resolved {p} ({size} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
